export interface PagedResult<T> { items: T[]; totalCount: number; page: number; pageSize: number; totalPages: number }
export interface CollectionDashboard { totalCases: number; totalOutstanding: number; totalOverdue: number; assignedCases: number; unassignedCases: number; activeCollectors: number; collectedToday: number; collectedMonthToDate: number; achievementPercent: number; activePromises: number; promisesDueToday: number; brokenPromises: number; visitsToday: number; pendingReviews: number; openComplaints: number; highRiskCases: number }
export interface ClientCard { id: string; code: string; name: string; organizationType: string; logoUrl?: string; activePortfolios: number; totalCases: number; totalOutstanding: number; assignedCases: number; unassignedCases: number; activeCollectors: number; collectedToday: number; achievementPercent: number; promiseAmount: number; brokenPromiseAmount: number; health: string; isActive: boolean }
export interface CollectionCase { id: string; caseNumber: string; customerCode: string; customerName: string; accountReference: string; clientName: string; portfolioName: string; outstandingBalance: number; overdueBalance: number; daysPastDue: number; bucket: string; status: string; priority: string; priorityScore: number; priorityExplanation: string; assignedCollectorId?: string; assignedCollectorName?: string; nextFollowUpAt?: string }
export interface Activity { id: string; type: string; result?: string; notes?: string; channel?: string; createdBy: string; createdAt: string; nextFollowUpAt?: string }
export interface PromiseItem { id: string; caseId: string; caseNumber: string; customerName: string; promisedAmount: number; promiseDate: string; actualPaidAmount: number; status: string; collectorName: string; channel: string; createdAt: string }
export interface PaymentItem { id: string; caseId: string; caseNumber: string; customerName: string; amount: number; paymentDate: string; method: string; referenceNumber: string; status: string; submittedBy: string; submittedAt: string; verifiedBy?: string; verifiedAt?: string; rejectionReason?: string }
export interface CaseDetails { id: string; caseNumber: string; clientName: string; portfolioName: string; customerCode: string; customerName: string; nationalId: string; primaryPhone: string; alternatePhone: string; address: string; governorate?: string; area?: string; accountReference: string; contractReference?: string; productType?: string; originalAmount: number; outstandingBalance: number; overdueBalance: number; penalties: number; fees: number; totalDue: number; daysPastDue: number; bucket: string; status: string; priority: string; priorityScore: number; priorityExplanation: string; assignedCollectorName?: string; sensitiveValuesRevealed: boolean; recommendedActionCode: string; recommendedActionReason: string; timeline: Activity[]; promises: PromiseItem[]; payments: PaymentItem[] }
export interface WorkQueue { callsDue: CollectionCase[]; highPriorityCases: CollectionCase[]; promisesDue: PromiseItem[]; brokenPromises: PromiseItem[]; visitsToday: number; pendingReviews: number; openComplaints: number }
export interface AssignmentPreviewItem { collectorId: string; collectorName: string; currentWorkload: number; proposedAdditionalCases: number; resultingWorkload: number }
export interface AssignmentPreview { caseCount: number; collectors: AssignmentPreviewItem[] }
export interface AutoAssignmentPreview extends AssignmentPreview { ruleCode: string; assignments: { caseId: string; caseNumber: string; collectorId: string; collectorName: string; reason: string }[] }
export interface CollectorLookup { id: string; name: string; activeWorkload: number; teamId?: string; teamName?: string }
export interface FieldVisit { id: string; caseId: string; caseNumber: string; customerName: string; collectorId: string; collectorName: string; scheduledAt: string; status: string; address: string; governorate?: string; area?: string; result?: string; notes?: string }
export interface Complaint { id: string; caseId: string; caseNumber: string; customerName: string; clientName: string; reference: string; source: string; category: string; severity: string; description: string; receivedAt: string; slaDueAt: string; slaStatus: string; status: string; ownerId: string; ownerName: string; resolution?: string; closedAt?: string }
export interface CollectionAudit { id: string; userName: string; action: string; entityType: string; entityId: string; caseId?: string; beforeJson?: string; afterJson?: string; source?: string; occurredAt: string }
export interface PortfolioLookup { id: string; organizationId: string; code: string; name: string; currencyCode: string; isActive: boolean }
export interface ImportBatch { id: string; organizationId: string; organizationName: string; portfolioId: string; portfolioName: string; fileName: string; status: string; totalRows: number; validRows: number; invalidRows: number; insertedRows: number; updatedRows: number; skippedRows: number; uploadedBy: string; uploadedAt: string; previewedAt?: string; confirmedAt?: string; failureReason?: string }
export interface ImportRow { id: string; rowNumber: number; accountReference: string; customerCode: string; customerName?: string; outstandingBalance?: number; overdueBalance?: number; daysPastDue?: number; isValid: boolean; errors: string[] }
export interface ImportPreview { batch: ImportBatch; rows: PagedResult<ImportRow> }
export interface ClientConfiguration { id: string; code: string; nameArabic: string; nameEnglish: string; organizationType: string; logoUrl?: string; contactEmail?: string; contactPhone?: string; settingsJson: string; isActive: boolean }
export interface PortfolioConfiguration { id: string; organizationId: string; code: string; nameArabic: string; nameEnglish: string; currencyCode: string; targetAmount?: number; settingsJson: string; isActive: boolean }
export interface BucketConfiguration { id: string; organizationId: string; portfolioId?: string; code: string; nameArabic: string; nameEnglish: string; minimumDays?: number; maximumDays?: number; sortOrder: number; isActive: boolean }
export interface CollectionsConfiguration { clients: ClientConfiguration[]; portfolios: PortfolioConfiguration[]; buckets: BucketConfiguration[] }
export interface CollectionAttachment { id: string; caseId: string; paymentId?: string; category: string; originalFileName: string; contentType: string; fileSize: number; uploadedBy: string; uploadedAt: string }
export interface CollectionReportSummary { totalCases: number; outstanding: number; overdue: number; approvedCollection: number; promiseAmount: number; fulfilledPromiseAmount: number; recoveryRate: number; promiseFulfillmentRate: number }
export interface CollectionReportBreakdown { code: string; name: string; cases: number; outstanding: number; overdue: number; collected: number; promiseAmount: number; fulfilledPromiseAmount: number }
export interface CollectionReport { filters: { organizationId?: string; portfolioId?: string; collectorId?: string; from: string; to: string }; summary: CollectionReportSummary; byClient: CollectionReportBreakdown[]; byBucket: CollectionReportBreakdown[]; byCollector: CollectionReportBreakdown[] }
export interface CaseFilters { page?: number; pageSize?: number; search?: string; organizationId?: string; portfolioId?: string; collectorId?: string; bucket?: string; status?: string; priority?: string }
