using System.Globalization;
using System.Text;
using Microsoft.EntityFrameworkCore;
using MIS.Application.Common;
using MIS.Application.DTOs.Collections;
using MIS.Application.Interfaces;
using MIS.Domain.Constants;
using MIS.Domain.Entities;
using MIS.Infrastructure.Persistence;

namespace MIS.Infrastructure.Services;

public sealed class CollectionsReportService : ICollectionsReportService
{
    private readonly ApplicationDbContext _db; private readonly ICurrentUserContext _user;
    public CollectionsReportService(ApplicationDbContext db, ICurrentUserContext user) { _db = db; _user = user; }
    public async Task<CollectionReportDto> GetExecutiveAsync(CollectionReportFilters filters, CancellationToken token)
    {
        Validate(filters); var ar = ApiTextLocalizer.IsArabic; var cases = AccessibleCases().AsNoTracking(); if (filters.OrganizationId.HasValue) cases = cases.Where(x => x.Portfolio.OrganizationId == filters.OrganizationId); if (filters.PortfolioId.HasValue) cases = cases.Where(x => x.PortfolioId == filters.PortfolioId); if (filters.CollectorId.HasValue) cases = cases.Where(x => x.AssignedCollectorId == filters.CollectorId);
        var payments = _db.CollectionPayments.AsNoTracking().Where(x => x.Status == CollectionsValues.PaymentStatuses.Approved && x.PaymentDate >= filters.From && x.PaymentDate <= filters.To && cases.Any(c => c.Id == x.CaseId)); var promises = _db.CollectionPromisesToPay.AsNoTracking().Where(x => x.PromiseDate >= filters.From && x.PromiseDate <= filters.To && cases.Any(c => c.Id == x.CaseId));
        var caseSummary = await cases.GroupBy(_ => 1).Select(g => new { Cases = g.Count(), Outstanding = g.Sum(x => x.OutstandingBalance), Overdue = g.Sum(x => x.OverdueBalance) }).SingleOrDefaultAsync(token); var collected = await payments.SumAsync(x => (decimal?)x.Amount, token) ?? 0; var promised = await promises.SumAsync(x => (decimal?)x.PromisedAmount, token) ?? 0; var fulfilled = await promises.Where(x => x.Status == CollectionsValues.PromiseStatuses.Fulfilled).SumAsync(x => (decimal?)x.ActualPaidAmount, token) ?? 0;
        var byClientBase = await cases.GroupBy(x => new { x.Portfolio.OrganizationId, x.Portfolio.Organization.Code, Name = ar ? x.Portfolio.Organization.NameArabic : x.Portfolio.Organization.NameEnglish }).Select(g => new { g.Key.OrganizationId, g.Key.Code, g.Key.Name, Cases = g.Count(), Outstanding = g.Sum(x => x.OutstandingBalance), Overdue = g.Sum(x => x.OverdueBalance) }).OrderByDescending(x => x.Outstanding).ToArrayAsync(token);
        var clientPayments = await payments.GroupBy(x => x.Case.Portfolio.OrganizationId).Select(g => new { Id = g.Key, Amount = g.Sum(x => x.Amount) }).ToDictionaryAsync(x => x.Id, token); var clientPromises = await promises.GroupBy(x => x.Case.Portfolio.OrganizationId).Select(g => new { Id = g.Key, Amount = g.Sum(x => x.PromisedAmount), Fulfilled = g.Where(x => x.Status == CollectionsValues.PromiseStatuses.Fulfilled).Sum(x => x.ActualPaidAmount) }).ToDictionaryAsync(x => x.Id, token);
        var byClient = byClientBase.Select(x => { clientPayments.TryGetValue(x.OrganizationId, out var pay); clientPromises.TryGetValue(x.OrganizationId, out var ptp); return new CollectionReportBreakdownDto(x.Code, x.Name, x.Cases, x.Outstanding, x.Overdue, pay?.Amount ?? 0, ptp?.Amount ?? 0, ptp?.Fulfilled ?? 0); }).ToArray();
        var bucketBase = await cases.GroupBy(x => new { x.CurrentBucketId, x.CurrentBucket.Code, Name = ar ? x.CurrentBucket.NameArabic : x.CurrentBucket.NameEnglish }).Select(g => new { Id = g.Key.CurrentBucketId, g.Key.Code, g.Key.Name, Cases = g.Count(), Outstanding = g.Sum(x => x.OutstandingBalance), Overdue = g.Sum(x => x.OverdueBalance) }).OrderByDescending(x => x.Overdue).ToArrayAsync(token); var bucketPayments = await payments.GroupBy(x => x.Case.CurrentBucketId).Select(g => new { Id = g.Key, Amount = g.Sum(x => x.Amount) }).ToDictionaryAsync(x => x.Id, token); var bucketPromises = await promises.GroupBy(x => x.Case.CurrentBucketId).Select(g => new { Id = g.Key, Amount = g.Sum(x => x.PromisedAmount), Fulfilled = g.Where(x => x.Status == CollectionsValues.PromiseStatuses.Fulfilled).Sum(x => x.ActualPaidAmount) }).ToDictionaryAsync(x => x.Id, token); var byBucket = bucketBase.Select(x => { bucketPayments.TryGetValue(x.Id, out var pay); bucketPromises.TryGetValue(x.Id, out var ptp); return new CollectionReportBreakdownDto(x.Code, x.Name, x.Cases, x.Outstanding, x.Overdue, pay?.Amount ?? 0, ptp?.Amount ?? 0, ptp?.Fulfilled ?? 0); }).ToArray();
        var collectorBase = await cases.Where(x => x.AssignedCollectorId != null).GroupBy(x => new { Id = x.AssignedCollectorId!.Value, x.AssignedCollector!.Username, x.AssignedCollector.FullName }).Select(g => new { g.Key.Id, Code = g.Key.Username, Name = g.Key.FullName, Cases = g.Count(), Outstanding = g.Sum(x => x.OutstandingBalance), Overdue = g.Sum(x => x.OverdueBalance) }).OrderByDescending(x => x.Outstanding).ToArrayAsync(token); var collectorPayments = await payments.Where(x => x.Case.AssignedCollectorId != null).GroupBy(x => x.Case.AssignedCollectorId!.Value).Select(g => new { Id = g.Key, Amount = g.Sum(x => x.Amount) }).ToDictionaryAsync(x => x.Id, token); var collectorPromises = await promises.GroupBy(x => x.CollectorId).Select(g => new { Id = g.Key, Amount = g.Sum(x => x.PromisedAmount), Fulfilled = g.Where(x => x.Status == CollectionsValues.PromiseStatuses.Fulfilled).Sum(x => x.ActualPaidAmount) }).ToDictionaryAsync(x => x.Id, token); var byCollector = collectorBase.Select(x => { collectorPayments.TryGetValue(x.Id, out var pay); collectorPromises.TryGetValue(x.Id, out var ptp); return new CollectionReportBreakdownDto(x.Code, x.Name, x.Cases, x.Outstanding, x.Overdue, pay?.Amount ?? 0, ptp?.Amount ?? 0, ptp?.Fulfilled ?? 0); }).ToArray();
        var overdue = caseSummary?.Overdue ?? 0; return new CollectionReportDto(filters, new CollectionReportSummaryDto(caseSummary?.Cases ?? 0, caseSummary?.Outstanding ?? 0, overdue, collected, promised, fulfilled, overdue <= 0 ? 0 : Math.Round(collected / overdue * 100, 2), promised <= 0 ? 0 : Math.Round(fulfilled / promised * 100, 2)), byClient, byBucket, byCollector);
    }
    public async Task<byte[]> ExportExecutiveCsvAsync(CollectionReportFilters filters, CancellationToken token)
    {
        if (!CanExport()) throw new HrForbiddenException("You do not have permission to export Collections reports."); var report = await GetExecutiveAsync(filters, token); var csv = new StringBuilder("Section,Code,Name,Cases,Outstanding,Overdue,Collected,PromiseAmount,FulfilledPromiseAmount\r\n"); Append(csv, "Client", report.ByClient); Append(csv, "Bucket", report.ByBucket); Append(csv, "Collector", report.ByCollector); _db.CollectionAuditLogs.Add(new CollectionAuditLog(_user.UserId, "CollectionsReportExported", "ExecutiveReport", Guid.NewGuid(), null, null, null, "EXPORT", DateTimeOffset.UtcNow)); await _db.SaveChangesAsync(token); return new UTF8Encoding(true).GetBytes(csv.ToString());
    }
    private IQueryable<CollectionCase> AccessibleCases() { var userId = _user.UserId; if (HasRole(SystemRoleNames.Admin) || HasRole(SystemRoleNames.CollectionsOperationsManager) || HasRole(SystemRoleNames.CollectionsReviewer) || HasRole(SystemRoleNames.CollectionsAuditor)) return _db.CollectionCases; var supervisor = HasRole(SystemRoleNames.CollectionsSupervisor); var collector = HasRole(SystemRoleNames.CollectionsCollector); var viewer = HasRole(SystemRoleNames.CollectionsClientViewer); return _db.CollectionCases.Where(x => (collector && x.AssignedCollectorId == userId) || (supervisor && ((x.AssignedTeam != null && x.AssignedTeam.SupervisorId == userId) || (x.AssignedTeamId == null && _db.CollectionUserAccess.Any(a => a.UserId == userId && a.OrganizationId == x.Portfolio.OrganizationId && (a.PortfolioId == null || a.PortfolioId == x.PortfolioId))))) || (viewer && _db.CollectionUserAccess.Any(a => a.UserId == userId && a.OrganizationId == x.Portfolio.OrganizationId && (a.PortfolioId == null || a.PortfolioId == x.PortfolioId)))); }
    private bool HasRole(string role) => _user.Roles.Contains(role, StringComparer.OrdinalIgnoreCase); private bool CanExport() => HasRole(SystemRoleNames.Admin) || HasRole(SystemRoleNames.CollectionsOperationsManager) || HasRole(SystemRoleNames.CollectionsSupervisor) || HasRole(SystemRoleNames.CollectionsAuditor);
    private static void Validate(CollectionReportFilters filters) { if (filters.From == default || filters.To == default || filters.To < filters.From || filters.To.DayNumber - filters.From.DayNumber > 730) throw new HrValidationException("Report date range must be valid and cannot exceed two years."); }
    private static void Append(StringBuilder csv, string section, IReadOnlyCollection<CollectionReportBreakdownDto> rows) { foreach (var x in rows) csv.Append(Escape(section)).Append(',').Append(Escape(x.Code)).Append(',').Append(Escape(x.Name)).Append(',').Append(x.Cases).Append(',').Append(x.Outstanding.ToString(CultureInfo.InvariantCulture)).Append(',').Append(x.Overdue.ToString(CultureInfo.InvariantCulture)).Append(',').Append(x.Collected.ToString(CultureInfo.InvariantCulture)).Append(',').Append(x.PromiseAmount.ToString(CultureInfo.InvariantCulture)).Append(',').Append(x.FulfilledPromiseAmount.ToString(CultureInfo.InvariantCulture)).Append("\r\n"); }
    private static string Escape(string value) { if (value.Length > 0 && "=+-@".Contains(value[0])) value = "'" + value; return '"' + value.Replace("\"", "\"\"") + '"'; }
}
