import { useLocalization } from '../../../context/LocalizationContext';

const en = {
  nextBestAction: 'Next best action', ESCALATE_COMPLAINT: 'Escalate complaint', REVIEW_PAYMENT: 'Review submitted collection', FOLLOW_UP_BROKEN_PTP: 'Follow up broken PTP', FOLLOW_UP_DUE_PTP: 'Follow up PTP due today', CONTACT_CUSTOMER: 'Contact customer', MONITOR_CASE: 'Monitor case', relatedPayment: 'Related collection',
  commandCenter: 'Collections Command Center', collections: 'Collections & Recovery', overview: 'Overview', clients: 'Clients & Portfolios', cases: 'Case Workbench', promises: 'PTP Hub', payments: 'Daily Collections', assignments: 'Assignment Center', visits: 'Field Visits', audit: 'Audit Log', imports: 'Import Center', settings: 'Configuration', reports: 'Reporting Center',
  dashboardSubtitle: 'Live portfolio health, commitments, reviews, and today’s operational workload.', totalCases: 'Total cases', totalOutstanding: 'Total outstanding', totalOverdue: 'Total overdue', assigned: 'Assigned', unassigned: 'Unassigned', activeCollectors: 'Active collectors', collectedToday: 'Collected today', collectedMtd: 'Collected MTD', achievement: 'Achievement', activePtp: 'Active PTP', dueToday: 'Due today', brokenPtp: 'Broken PTP', visitsToday: 'Visits today', pendingReviews: 'Pending reviews', complaints: 'Open complaints', highRisk: 'High risk cases',
  myWork: 'My work today', callsDue: 'Calls due', priorityCases: 'High priority', noWork: 'No matching work items.', openCase: 'Open case', clientCenterSubtitle: 'Configurable creditor organizations and their operational portfolio health.', searchClients: 'Search clients…', allTypes: 'All organization types', portfolios: 'Portfolios', casesCount: 'Cases', health: 'Health', noClients: 'No clients match these filters.',
  caseWorkbenchSubtitle: 'Server-side search and prioritization across authorized collection cases.', searchCases: 'Search case, customer, account, contract…', allPriorities: 'All priorities', allStatuses: 'All statuses', customer: 'Customer', clientPortfolio: 'Client / portfolio', balance: 'Outstanding', overdue: 'Overdue', dpdBucket: 'DPD / bucket', collector: 'Collector', priority: 'Priority', noCases: 'No cases match these filters.',
  case360: 'Case 360°', backToCases: 'Back to cases', customerIdentity: 'Customer identity', financialPosition: 'Financial position', nationalId: 'National ID', phone: 'Phone', alternatePhone: 'Alternate phone', address: 'Address', accountReference: 'Account reference', contractReference: 'Contract reference', product: 'Product', originalAmount: 'Original amount', feesPenalties: 'Fees / penalties', reveal: 'Reveal sensitive data', revealed: 'Sensitive values revealed and audited', timeline: 'Activity timeline', addActivity: 'Add activity', activityType: 'Activity type', result: 'Result', notes: 'Notes', channel: 'Channel', nextFollowUp: 'Next follow-up', saveActivity: 'Save activity', addPromise: 'Create PTP', amount: 'Amount', promiseDate: 'Promise date', submitPromise: 'Create promise', submitCollection: 'Submit collection', paymentDate: 'Payment date', method: 'Method', reference: 'Reference number', submit: 'Submit', noActivity: 'No activity recorded yet.',
  ptpSubtitle: 'Promises are evaluated deterministically against approved payments and due-date policy.', status: 'Status', actualPaid: 'Actual paid', date: 'Date', noPromises: 'No promises match these filters.', dcrSubtitle: 'Maker-checker review of submitted collection transactions.', submittedBy: 'Submitted by', approve: 'Approve', reject: 'Reject', rejectionReason: 'Rejection reason', noPayments: 'No collection transactions match these filters.',
  assignmentSubtitle: 'Select authorized cases, preview the workload impact, then confirm an auditable assignment.', selectedCases: 'Selected cases', selectCollector: 'Select collector', currentWorkload: 'Current workload', resultingWorkload: 'Resulting workload', assignmentReason: 'Assignment reason', previewAssignment: 'Preview assignment', confirmAssignment: 'Confirm assignment', assignmentComplete: 'Cases assigned successfully.', noCollectors: 'No eligible collectors are available.', selectCasesHelp: 'Select one or more cases from the server-side list.',
  manualDistribution: 'Manual', automaticDistribution: 'Automatic balancing', maximumCapacity: 'Maximum active capacity', distributionRule: 'Rule', branding: 'Bank branding',
  visitsSubtitle: 'Plan, assign, and record field outcomes without fabricating GPS data.', scheduleVisit: 'Schedule visit', scheduledAt: 'Scheduled at', completeVisit: 'Complete visit', visitResult: 'Visit result', noVisits: 'No visits match these filters.', complaintsSubtitle: 'Case-linked complaints with configurable SLA deadlines and escalation visibility.', newComplaint: 'New complaint', category: 'Category', severity: 'Severity', owner: 'Owner', sla: 'SLA', description: 'Description', resolution: 'Resolution', changeStatus: 'Change status', noComplaints: 'No complaints match these filters.', auditSubtitle: 'Immutable history of sensitive and operational collection events.', action: 'Action', entity: 'Entity', user: 'User', source: 'Source', noAudit: 'No audit events match these filters.', PLANNED: 'Planned', ASSIGNED: 'Assigned', COMPLETED: 'Completed', FAILED: 'Failed', NEW: 'New', IN_PROGRESS: 'In progress', RESOLVED: 'Resolved', CLOSED: 'Closed', ESCALATED: 'Escalated', ON_TIME: 'On time', APPROACHING: 'Approaching SLA', BREACHED: 'Breached',
  importSubtitle: 'Upload CSV/XLSX, validate every row, review errors, then explicitly confirm the safe upsert.', uploadFile: 'Upload file', selectClient: 'Select client', selectPortfolio: 'Select portfolio', file: 'File', uploadPreview: 'Upload & validate', totalRows: 'Total rows', validRows: 'Valid rows', invalidRows: 'Invalid rows', insertedRows: 'Inserted', updatedRows: 'Updated', skippedRows: 'Skipped', preview: 'Preview', confirmImport: 'Confirm import', downloadErrors: 'Download errors', importHistory: 'Import history', noImports: 'No collection imports yet.', row: 'Row', errors: 'Errors', PREVIEW_READY: 'Preview ready', UPLOADED: 'Uploaded',
  settingsSubtitle: 'Onboard clients and configure portfolios, targets, PTP policy, and delinquency buckets without code changes.', addClient: 'Add client', addPortfolio: 'Add portfolio', addBucket: 'Add bucket', nameArabic: 'Arabic name', nameEnglish: 'English name', code: 'Code', organizationType: 'Organization type', target: 'Target', currencyCode: 'Currency', minimumDays: 'Minimum days', maximumDays: 'Maximum days', sortOrder: 'Sort order', active: 'Active', configurationJson: 'Advanced settings (JSON)', edit: 'Edit',
  attachments: 'Documents & attachments', uploadAttachment: 'Upload attachment', attachmentCategory: 'Category', noAttachments: 'No documents attached to this case.', fileSize: 'File size', CASE_DOCUMENT: 'Case document', PAYMENT_PROOF: 'Payment proof', VISIT_EVIDENCE: 'Visit evidence', COMPLAINT_DOCUMENT: 'Complaint document', SETTLEMENT_DOCUMENT: 'Settlement document',
  reportsSubtitle: 'Consistent server-calculated KPIs and authorized portfolio, bucket, and collector performance exports.', from: 'From', to: 'To', runReport: 'Run report', exportCsv: 'Export CSV', approvedCollection: 'Approved collection', recoveryRate: 'Recovery rate', fulfillmentRate: 'PTP fulfillment', byClient: 'By client', byBucket: 'By bucket', byCollector: 'By collector', collected: 'Collected', fulfilledAmount: 'Fulfilled amount',
  loading: 'Loading…', loadError: 'Could not load collections data.', saveError: 'The operation could not be completed.', saved: 'Operation completed successfully.', currency: 'EGP', language: 'Language', signOut: 'Sign out', navigation: 'Collections navigation', openNavigation: 'Open navigation', closeNavigation: 'Close navigation',
  ACTIVE: 'Active', UPCOMING: 'Upcoming', DUE_TODAY: 'Due today', BROKEN: 'Broken', PARTIALLY_FULFILLED: 'Partially fulfilled', FULFILLED: 'Fulfilled', CANCELLED: 'Cancelled', SUBMITTED: 'Submitted', UNDER_REVIEW: 'Under review', APPROVED: 'Approved', REJECTED: 'Rejected', HIGH: 'High', MEDIUM: 'Medium', NORMAL: 'Normal', HEALTHY: 'Healthy', WATCH: 'Watch', AT_RISK: 'At risk', NO_DATA: 'No data',
};

const ar: typeof en = {
  nextBestAction: 'الإجراء التالي المقترح', ESCALATE_COMPLAINT: 'تصعيد الشكوى', REVIEW_PAYMENT: 'مراجعة التحصيل المقدم', FOLLOW_UP_BROKEN_PTP: 'متابعة وعد السداد المكسور', FOLLOW_UP_DUE_PTP: 'متابعة وعد السداد المستحق اليوم', CONTACT_CUSTOMER: 'التواصل مع العميل', MONITOR_CASE: 'متابعة الحالة', relatedPayment: 'التحصيل المرتبط',
  commandCenter: 'مركز قيادة التحصيل', collections: 'التحصيل والاسترداد', overview: 'نظرة عامة', clients: 'العملاء والمحافظ', cases: 'منصة الحالات', promises: 'مركز وعود السداد', payments: 'التحصيل اليومي', assignments: 'مركز التوزيع', visits: 'الزيارات الميدانية', audit: 'سجل التدقيق', imports: 'مركز الاستيراد', settings: 'الإعدادات', reports: 'مركز التقارير',
  dashboardSubtitle: 'متابعة لحظية لصحة المحافظ والالتزامات والمراجعات وحجم عمل اليوم.', totalCases: 'إجمالي الحالات', totalOutstanding: 'إجمالي المديونية', totalOverdue: 'إجمالي المتأخر', assigned: 'موزع', unassigned: 'غير موزع', activeCollectors: 'المحصلون النشطون', collectedToday: 'تحصيل اليوم', collectedMtd: 'تحصيل الشهر', achievement: 'نسبة الإنجاز', activePtp: 'وعود نشطة', dueToday: 'مستحق اليوم', brokenPtp: 'وعود مكسورة', visitsToday: 'زيارات اليوم', pendingReviews: 'بانتظار المراجعة', complaints: 'شكاوى مفتوحة', highRisk: 'حالات مرتفعة الخطورة',
  myWork: 'عملي اليوم', callsDue: 'اتصالات مستحقة', priorityCases: 'أولوية مرتفعة', noWork: 'لا توجد مهام مطابقة.', openCase: 'فتح الحالة', clientCenterSubtitle: 'جهات دائنة قابلة للتهيئة مع متابعة الصحة التشغيلية لمحافظها.', searchClients: 'ابحث عن عميل…', allTypes: 'كل أنواع الجهات', portfolios: 'المحافظ', casesCount: 'الحالات', health: 'الصحة', noClients: 'لا توجد جهات مطابقة للفلاتر.',
  caseWorkbenchSubtitle: 'بحث وترتيب أولوية من الخادم عبر حالات التحصيل المصرح بها.', searchCases: 'ابحث بالحالة أو العميل أو الحساب أو العقد…', allPriorities: 'كل الأولويات', allStatuses: 'كل الحالات', customer: 'العميل', clientPortfolio: 'العميل / المحفظة', balance: 'الرصيد القائم', overdue: 'المتأخر', dpdBucket: 'أيام التأخر / الفئة', collector: 'المحصل', priority: 'الأولوية', noCases: 'لا توجد حالات مطابقة للفلاتر.',
  case360: 'عرض الحالة 360°', backToCases: 'العودة للحالات', customerIdentity: 'هوية العميل', financialPosition: 'الموقف المالي', nationalId: 'الرقم القومي', phone: 'الهاتف', alternatePhone: 'هاتف بديل', address: 'العنوان', accountReference: 'مرجع الحساب', contractReference: 'مرجع العقد', product: 'المنتج', originalAmount: 'المبلغ الأصلي', feesPenalties: 'الرسوم / الغرامات', reveal: 'إظهار البيانات الحساسة', revealed: 'تم إظهار البيانات وتسجيل العملية', timeline: 'الخط الزمني للنشاط', addActivity: 'إضافة نشاط', activityType: 'نوع النشاط', result: 'النتيجة', notes: 'ملاحظات', channel: 'القناة', nextFollowUp: 'المتابعة القادمة', saveActivity: 'حفظ النشاط', addPromise: 'إنشاء وعد سداد', amount: 'المبلغ', promiseDate: 'تاريخ الوعد', submitPromise: 'إنشاء الوعد', submitCollection: 'تسجيل تحصيل', paymentDate: 'تاريخ السداد', method: 'وسيلة السداد', reference: 'الرقم المرجعي', submit: 'إرسال', noActivity: 'لا توجد أنشطة مسجلة بعد.',
  ptpSubtitle: 'تُقيّم وعود السداد بقواعد حتمية وفق المدفوعات المعتمدة وسياسة الاستحقاق.', status: 'الحالة', actualPaid: 'المدفوع الفعلي', date: 'التاريخ', noPromises: 'لا توجد وعود مطابقة للفلاتر.', dcrSubtitle: 'مراجعة التحصيلات المقدمة وفق مبدأ المُنشئ والمراجع.', submittedBy: 'مقدم بواسطة', approve: 'اعتماد', reject: 'رفض', rejectionReason: 'سبب الرفض', noPayments: 'لا توجد معاملات تحصيل مطابقة للفلاتر.',
  assignmentSubtitle: 'اختر الحالات المصرح بها، وراجع أثر التوزيع على الأحمال، ثم أكد العملية لتسجيلها بالكامل.', selectedCases: 'الحالات المختارة', selectCollector: 'اختر المحصل', currentWorkload: 'الحمل الحالي', resultingWorkload: 'الحمل بعد التوزيع', assignmentReason: 'سبب التوزيع', previewAssignment: 'معاينة التوزيع', confirmAssignment: 'تأكيد التوزيع', assignmentComplete: 'تم توزيع الحالات بنجاح.', noCollectors: 'لا يوجد محصلون مؤهلون متاحون.', selectCasesHelp: 'اختر حالة أو أكثر من القائمة المحملة من الخادم.',
  manualDistribution: 'توزيع يدوي', automaticDistribution: 'موازنة تلقائية', maximumCapacity: 'الحد الأقصى للحالات النشطة', distributionRule: 'القاعدة', branding: 'هوية البنوك',
  visitsSubtitle: 'تخطيط الزيارات وتوزيعها وتسجيل نتائجها دون ادعاء وجود بيانات GPS.', scheduleVisit: 'جدولة زيارة', scheduledAt: 'الموعد', completeVisit: 'إكمال الزيارة', visitResult: 'نتيجة الزيارة', noVisits: 'لا توجد زيارات مطابقة للفلاتر.', complaintsSubtitle: 'شكاوى مرتبطة بالحالات مع مواعيد SLA قابلة للتهيئة ومؤشرات التصعيد.', newComplaint: 'شكوى جديدة', category: 'التصنيف', severity: 'الخطورة', owner: 'المسؤول', sla: 'اتفاقية الخدمة', description: 'الوصف', resolution: 'الحل', changeStatus: 'تغيير الحالة', noComplaints: 'لا توجد شكاوى مطابقة للفلاتر.', auditSubtitle: 'سجل غير قابل للتعديل للأحداث الحساسة والتشغيلية في التحصيل.', action: 'الإجراء', entity: 'الكيان', user: 'المستخدم', source: 'المصدر', noAudit: 'لا توجد أحداث تدقيق مطابقة للفلاتر.', PLANNED: 'مخططة', ASSIGNED: 'موزعة', COMPLETED: 'مكتملة', FAILED: 'فاشلة', NEW: 'جديدة', IN_PROGRESS: 'قيد التنفيذ', RESOLVED: 'تم الحل', CLOSED: 'مغلقة', ESCALATED: 'مصعدة', ON_TIME: 'في الموعد', APPROACHING: 'قرب تجاوز SLA', BREACHED: 'متجاوزة',
  importSubtitle: 'ارفع CSV/XLSX، تحقق من كل صف، راجع الأخطاء، ثم أكد الـ upsert الآمن صراحةً.', uploadFile: 'رفع ملف', selectClient: 'اختر العميل', selectPortfolio: 'اختر المحفظة', file: 'الملف', uploadPreview: 'رفع وتحليل', totalRows: 'إجمالي الصفوف', validRows: 'صفوف صحيحة', invalidRows: 'صفوف خاطئة', insertedRows: 'تمت الإضافة', updatedRows: 'تم التحديث', skippedRows: 'تم التجاوز', preview: 'المعاينة', confirmImport: 'تأكيد الاستيراد', downloadErrors: 'تنزيل الأخطاء', importHistory: 'سجل الاستيراد', noImports: 'لا توجد عمليات استيراد بعد.', row: 'الصف', errors: 'الأخطاء', PREVIEW_READY: 'المعاينة جاهزة', UPLOADED: 'تم الرفع',
  settingsSubtitle: 'إضافة العملاء وتهيئة المحافظ والأهداف وسياسة وعود السداد وفئات التأخر دون تعديل الكود.', addClient: 'إضافة عميل', addPortfolio: 'إضافة محفظة', addBucket: 'إضافة فئة', nameArabic: 'الاسم بالعربية', nameEnglish: 'الاسم بالإنجليزية', code: 'الكود', organizationType: 'نوع الجهة', target: 'الهدف', currencyCode: 'العملة', minimumDays: 'الحد الأدنى للأيام', maximumDays: 'الحد الأقصى للأيام', sortOrder: 'ترتيب العرض', active: 'نشط', configurationJson: 'الإعدادات المتقدمة (JSON)', edit: 'تعديل',
  attachments: 'المستندات والمرفقات', uploadAttachment: 'رفع مرفق', attachmentCategory: 'التصنيف', noAttachments: 'لا توجد مستندات مرفقة بهذه الحالة.', fileSize: 'حجم الملف', CASE_DOCUMENT: 'مستند حالة', PAYMENT_PROOF: 'إثبات سداد', VISIT_EVIDENCE: 'إثبات زيارة', COMPLAINT_DOCUMENT: 'مستند شكوى', SETTLEMENT_DOCUMENT: 'مستند تسوية',
  reportsSubtitle: 'مؤشرات موحدة محسوبة من الخادم وتصدير مصرح لأداء العملاء والفئات والمحصلين.', from: 'من', to: 'إلى', runReport: 'تشغيل التقرير', exportCsv: 'تصدير CSV', approvedCollection: 'التحصيل المعتمد', recoveryRate: 'معدل الاسترداد', fulfillmentRate: 'تنفيذ الوعود', byClient: 'حسب العميل', byBucket: 'حسب الفئة', byCollector: 'حسب المحصل', collected: 'المحصل', fulfilledAmount: 'المبلغ المنفذ',
  loading: 'جارٍ التحميل…', loadError: 'تعذر تحميل بيانات التحصيل.', saveError: 'تعذر إتمام العملية.', saved: 'تمت العملية بنجاح.', currency: 'ج.م', language: 'اللغة', signOut: 'تسجيل الخروج', navigation: 'تنقلات التحصيل', openNavigation: 'فتح القائمة', closeNavigation: 'إغلاق القائمة',
  ACTIVE: 'نشط', UPCOMING: 'قادم', DUE_TODAY: 'مستحق اليوم', BROKEN: 'مكسور', PARTIALLY_FULFILLED: 'منفذ جزئيًا', FULFILLED: 'منفذ', CANCELLED: 'ملغي', SUBMITTED: 'مقدم', UNDER_REVIEW: 'قيد المراجعة', APPROVED: 'معتمد', REJECTED: 'مرفوض', HIGH: 'مرتفعة', MEDIUM: 'متوسطة', NORMAL: 'عادية', HEALTHY: 'جيد', WATCH: 'تحت المتابعة', AT_RISK: 'معرض للخطر', NO_DATA: 'لا توجد بيانات',
};

export type CollectionsTranslationKey = keyof typeof en;
export function useCollectionsLocalization() {
  const localization = useLocalization();
  const dictionary = localization.language === 'ar' ? ar : en;
  return { ...localization, ct: (key: CollectionsTranslationKey | string) => dictionary[key as CollectionsTranslationKey] ?? key };
}
