import { CalendarDays, ChevronLeft, ChevronRight, Clock3, X } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useLocalization } from '../../context/LocalizationContext';

interface ProfessionalDateInputProps {
  id?: string; name?: string; value?: string; defaultValue?: string; onChange?: (value: string) => void;
  mode?: 'date' | 'datetime'; required?: boolean; min?: string; max?: string; disabled?: boolean; className?: string; ariaLabel?: string;
}

const pad = (value: number) => String(value).padStart(2, '0');
const isoDate = (date: Date) => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
const parseValue = (value?: string) => { if (!value) return null; const date = new Date(`${value.length === 10 ? value + 'T00:00' : value}`); return Number.isNaN(date.getTime()) ? null : date; };

export function ProfessionalDateInput({ id, name, value, defaultValue, onChange, mode = 'date', required, min, max, disabled, className = '', ariaLabel }: ProfessionalDateInputProps) {
  const { language, isRtl } = useLocalization(); const root = useRef<HTMLDivElement>(null); const controlled = value !== undefined;
  const [internal, setInternal] = useState(defaultValue ?? ''); const current = controlled ? value ?? '' : internal; const selected = parseValue(current);
  const [open, setOpen] = useState(false); const [view, setView] = useState(() => selected ?? new Date()); const [hour, setHour] = useState(() => pad(selected?.getHours() ?? 9)); const [minute, setMinute] = useState(() => pad(selected?.getMinutes() ?? 0));
  useEffect(() => { const next = parseValue(current); if (next) { setView(next); setHour(pad(next.getHours())); setMinute(pad(next.getMinutes())); } }, [current]);
  useEffect(() => { const close = (event: PointerEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close); }, []);
  useEffect(() => { const form = root.current?.closest('form'); if (!form || controlled) return; const reset = () => { setInternal(defaultValue ?? ''); setOpen(false); }; form.addEventListener('reset', reset); return () => form.removeEventListener('reset', reset); }, [controlled, defaultValue]);
  const locale = language === 'ar' ? 'ar-EG' : 'en-GB'; const labels = language === 'ar' ? { choose: mode === 'date' ? 'اختر التاريخ' : 'اختر التاريخ والوقت', today: 'اليوم', clear: 'مسح', done: 'تم', previous: 'الشهر السابق', next: 'الشهر التالي', time: 'الوقت' } : { choose: mode === 'date' ? 'Choose date' : 'Choose date & time', today: 'Today', clear: 'Clear', done: 'Done', previous: 'Previous month', next: 'Next month', time: 'Time' };
  const emit = (date: Date | null, close = mode === 'date') => { const next = date ? `${isoDate(date)}${mode === 'datetime' ? `T${hour}:${minute}` : ''}` : ''; if (!controlled) setInternal(next); onChange?.(next); if (close) setOpen(false); };
  const monthStart = new Date(view.getFullYear(), view.getMonth(), 1); const gridStart = new Date(monthStart); gridStart.setDate(1 - ((monthStart.getDay() + 6) % 7));
  const days = useMemo(() => Array.from({ length: 42 }, (_, index) => { const date = new Date(gridStart); date.setDate(gridStart.getDate() + index); return date; }), [gridStart.getTime()]);
  const weekdays = useMemo(() => Array.from({ length: 7 }, (_, index) => new Intl.DateTimeFormat(locale, { weekday: 'narrow' }).format(new Date(2024, 0, index + 1))), [locale]);
  const display = selected ? new Intl.DateTimeFormat(locale, mode === 'datetime' ? { dateStyle: 'medium', timeStyle: 'short' } : { dateStyle: 'medium' }).format(selected) : labels.choose;
  const minimum = min?.slice(0, 10) ?? ''; const maximum = max?.slice(0, 10) ?? '';
  const choose = (date: Date) => { const key = isoDate(date); if ((minimum && key < minimum) || (maximum && key > maximum)) return; setView(date); emit(date, mode === 'date'); };
  const applyTime = () => { const basis = selected ?? view; const next = new Date(basis.getFullYear(), basis.getMonth(), basis.getDate(), Number(hour), Number(minute)); emit(next, true); };
  return <div ref={root} className={`relative ${className}`}>
    <input aria-label={ariaLabel ?? labels.choose} className="pointer-events-none absolute h-px w-px opacity-0" name={name} onInvalid={() => setOpen(true)} readOnly required={required} tabIndex={-1} type="text" value={current} />
    <button id={id} type="button" disabled={disabled} aria-expanded={open} onClick={() => setOpen(value => !value)} className={`field flex min-h-12 items-center gap-3 text-start disabled:cursor-not-allowed disabled:bg-slate-100 disabled:opacity-70 ${selected ? 'text-slate-800' : 'text-slate-500'}`}><CalendarDays className="h-5 w-5 shrink-0 text-mis-primary" /><span className="min-w-0 flex-1 truncate">{display}</span>{selected && <span role="button" tabIndex={0} onClick={event => { event.stopPropagation(); emit(null); }} onKeyDown={event => { if (event.key === 'Enter') emit(null); }} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100"><X className="h-4 w-4" /></span>}</button>
    {open && <div dir={isRtl ? 'rtl' : 'ltr'} className="absolute z-50 mt-2 w-[min(22rem,calc(100vw-2rem))] rounded-2xl border border-mis-border bg-white p-4 shadow-2xl" style={{ insetInlineStart: 0 }}>
      <div className="flex items-center justify-between"><button type="button" aria-label={labels.previous} onClick={() => setView(new Date(view.getFullYear(), view.getMonth() - 1, 1))} className="rounded-xl p-2 text-slate-500 hover:bg-mis-pale hover:text-mis-primary"><ChevronLeft className={`h-5 w-5 ${isRtl ? 'rotate-180' : ''}`} /></button><strong className="text-sm text-mis-navy">{new Intl.DateTimeFormat(locale, { month: 'long', year: 'numeric' }).format(view)}</strong><button type="button" aria-label={labels.next} onClick={() => setView(new Date(view.getFullYear(), view.getMonth() + 1, 1))} className="rounded-xl p-2 text-slate-500 hover:bg-mis-pale hover:text-mis-primary"><ChevronRight className={`h-5 w-5 ${isRtl ? 'rotate-180' : ''}`} /></button></div>
      <div className="mt-3 grid grid-cols-7 text-center text-xs font-bold text-slate-400">{weekdays.map((day, index) => <span key={`${day}-${index}`} className="py-2">{day}</span>)}</div>
      <div className="grid grid-cols-7 gap-1">{days.map(day => { const key = isoDate(day); const active = selected && key === isoDate(selected); const today = key === isoDate(new Date()); const outside = day.getMonth() !== view.getMonth(); const dayDisabled = Boolean((minimum && key < minimum) || (maximum && key > maximum)); return <button type="button" disabled={dayDisabled} key={key} onClick={() => choose(day)} className={`grid h-9 place-items-center rounded-lg text-sm transition disabled:cursor-not-allowed disabled:opacity-25 ${active ? 'bg-mis-primary font-bold text-white shadow-sm' : today ? 'bg-mis-pale font-bold text-mis-primary' : outside ? 'text-slate-300 hover:bg-slate-50' : 'text-slate-700 hover:bg-mis-pale hover:text-mis-primary'}`}>{new Intl.NumberFormat(locale, { useGrouping: false }).format(day.getDate())}</button>; })}</div>
      {mode === 'datetime' && <div className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3"><Clock3 className="h-5 w-5 text-mis-primary" /><span className="text-xs font-bold text-slate-500">{labels.time}</span><div className="ms-auto flex items-center gap-1" dir="ltr"><select aria-label="Hour" value={hour} onChange={event => setHour(event.target.value)} className="rounded-lg border border-mis-border bg-white px-2 py-1.5 text-sm">{Array.from({ length: 24 }, (_, index) => pad(index)).map(item => <option key={item}>{item}</option>)}</select><span>:</span><select aria-label="Minute" value={minute} onChange={event => setMinute(event.target.value)} className="rounded-lg border border-mis-border bg-white px-2 py-1.5 text-sm">{['00', '05', '10', '15', '20', '25', '30', '35', '40', '45', '50', '55'].map(item => <option key={item}>{item}</option>)}</select></div></div>}
      <div className="mt-4 flex items-center gap-2 border-t border-mis-border pt-3"><button type="button" onClick={() => { const now = new Date(); setView(now); setHour(pad(now.getHours())); setMinute(pad(Math.floor(now.getMinutes() / 5) * 5)); emit(now, mode === 'date'); }} className="rounded-lg px-3 py-2 text-xs font-bold text-mis-primary hover:bg-mis-pale">{labels.today}</button><button type="button" onClick={() => emit(null)} className="rounded-lg px-3 py-2 text-xs font-bold text-slate-500 hover:bg-slate-100">{labels.clear}</button>{mode === 'datetime' && <button type="button" onClick={applyTime} className="ms-auto rounded-lg bg-mis-primary px-4 py-2 text-xs font-bold text-white">{labels.done}</button>}</div>
    </div>}
  </div>;
}
