import { Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { CollectionAudit, PagedResult } from '../../features/collections/types/collections';

export function CollectionAuditPage() { const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [data, setData] = useState<PagedResult<CollectionAudit>>(); const [error, setError] = useState(false); useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]); useEffect(() => { collectionsService.audit({ page, pageSize: 30, search: query }).then(setData).catch(() => setError(true)); }, [page, query]); return <div><PageHeader eyebrow={ct('collections')} title={ct('audit')} description={ct('auditSubtitle')} /><label className="relative mb-5 block max-w-xl"><Search className="absolute top-3.5 h-5 w-5 text-slate-400" style={{ insetInlineStart: '0.9rem' }} /><input className="field ps-12" value={search} onChange={e => setSearch(e.target.value)} placeholder={ct('action')} /></label>{error ? <ErrorState title={ct('loadError')} /> : !data ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-50"><tr>{[ct('date'), ct('user'), ct('action'), ct('entity'), ct('source')].map(x => <th key={x} className="px-5 py-4 text-start text-xs text-slate-500">{x}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(x => <tr key={x.id}><td className="px-5 py-4" data-bidi="ltr">{f.dateTime(x.occurredAt)}</td><td className="px-5 py-4">{x.userName}</td><td className="px-5 py-4 font-bold text-mis-navy">{x.action}</td><td className="px-5 py-4"><p>{x.entityType}</p><p className="text-xs text-slate-500" data-bidi="ltr">{x.entityId}</p></td><td className="px-5 py-4">{x.source || '—'}</td></tr>)}</tbody></table>{!data.items.length && <p className="p-12 text-center text-slate-500">{ct('noAudit')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>}</div>; }
