import { ImageUp, ShieldCheck } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { BankLogo } from '../../features/collections/components/BankLogo';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { ClientConfiguration } from '../../features/collections/types/collections';

export function CollectionsBrandingPage() {
  const { language, ct } = useCollectionsLocalization(); const [clients, setClients] = useState<ClientConfiguration[]>(); const [busy, setBusy] = useState<string>(); const [message, setMessage] = useState('');
  const load = () => collectionsService.configuration().then(value => setClients(value.clients)); useEffect(() => { void load(); }, []);
  const upload = async (event: FormEvent<HTMLFormElement>, client: ClientConfiguration) => { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get('file'); if (!(file instanceof File) || !file.size) return; setBusy(client.id); setMessage(''); try { await collectionsService.uploadClientLogo(client.id, file); await load(); setMessage(language === 'ar' ? 'تم تحديث الشعار بنجاح.' : 'Logo updated successfully.'); } catch { setMessage(ct('saveError')); } finally { setBusy(undefined); } };
  const title = language === 'ar' ? 'هوية البنوك والعملاء' : 'Bank & client branding'; const subtitle = language === 'ar' ? 'ارفع الشعار الرسمي لكل بنك ليظهر بوضوح في بطاقات العملاء ومساحات العمل.' : 'Upload each bank’s official logo for clear, consistent client recognition.';
  return <div><PageHeader eyebrow={ct('settings')} title={title} description={subtitle} />{message && <p className="mb-5 rounded-xl border border-mis-border bg-white p-4 text-sm font-semibold text-mis-primary">{message}</p>}{!clients ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{clients.map(client => { const name = language === 'ar' ? client.nameArabic : client.nameEnglish; return <article key={client.id} className="rounded-3xl border border-mis-border bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><BankLogo code={client.code} name={name} logoUrl={client.logoUrl} className="h-20 w-20" /><div className="min-w-0"><h2 className="truncate font-bold text-mis-navy">{name}</h2><p className="mt-1 text-xs font-semibold text-slate-400" data-bidi="ltr">{client.code}</p>{client.logoUrl && <span className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-emerald-700"><ShieldCheck className="h-3.5 w-3.5" />{language === 'ar' ? 'شعار رسمي مرفوع' : 'Custom logo uploaded'}</span>}</div></div><form onSubmit={event => upload(event, client)} className="mt-5"><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-mis-sky bg-mis-pale/40 p-3 text-sm font-semibold text-mis-primary hover:bg-mis-pale"><ImageUp className="h-5 w-5" /><span className="flex-1">{language === 'ar' ? 'اختيار PNG أو JPG أو WebP' : 'Choose PNG, JPG, or WebP'}</span><input name="file" type="file" accept=".png,.jpg,.jpeg,.webp" required className="sr-only" /></label><button disabled={busy === client.id} className="mt-3 w-full rounded-xl bg-mis-primary px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{busy === client.id ? ct('loading') : language === 'ar' ? 'حفظ الشعار' : 'Save logo'}</button></form></article>; })}</section>}</div>;
}
