export const translations = {
  en: {
    language: 'Language', english: 'English', arabic: 'العربية', dashboard: 'Dashboard', employees: 'Employees', delegations: 'Delegations', absences: 'Employee Absences', companyAbsences: 'Company Absences', employeeDocuments: 'Employee Documents', master: 'Master', logout: 'Logout', humanResources: 'Human Resources', hrDepartment: 'HR Department', collectionFirm: 'MIS Collection Firm',
    welcomeBack: 'Welcome Back', signInSubtitle: 'Sign in to your MIS account', username: 'Email / Username', usernamePlaceholder: 'admin or name@company.com', password: 'Password', passwordPlaceholder: 'Enter your password', rememberMe: 'Remember me', forgotPassword: 'Forgot Password?', signIn: 'Sign In', signingIn: 'Signing In', internalSystem: 'Internal Management System', secureTagline: 'Secure. Organized. Efficient.', collectionSystem: 'Collection Management System', invalidCredentials: 'Invalid username or password.', usernameRequired: 'Email or username is required.', passwordRequired: 'Password is required.',
    hrDashboard: 'HR Dashboard', dashboardSubtitle: 'Overview of your workforce and HR operations', totalEmployees: 'Total Employees', activeEmployees: 'Active Employees', absentToday: 'Absent Today', documentsAttention: 'Documents Requiring Attention', allEmployeeRecords: 'All employee records', noEmployeeRecords: 'No employee records yet', totalEmployeePercent: '{value}% of total employees', recordedToday: 'Recorded today', notAvailableYet: 'Not available yet', documentRecordsContext: '{count} document records · attention rules not available', totalDocumentsContext: '{count} total documents', employeeOverview: 'Employee Overview', noEmployeeData: 'No employee data yet', employeeDataHelp: 'Employees by department will appear here once employee records are available.', quickActions: 'Quick Actions', viewEmployeeDocuments: 'View Employee Documents', attendanceOverview: 'Attendance Overview', attendanceUnavailable: 'Attendance data is not available yet', attendanceHelp: 'Attendance information will appear here once the HR attendance module is implemented.', recentActivity: 'Recent Activity', noRecentActivity: 'No recent activity', noActivitySource: 'There is currently no activity data source for this dashboard.', noDocumentsAttention: 'No documents require attention', documentsAttentionHelp: 'Document attention rules have not been defined. Existing document records remain available in Employee Documents.', viewDocuments: 'View documents', dashboardUnavailable: 'Dashboard unavailable', tryAgain: 'Try again', loadDashboardError: 'Unable to load the HR dashboard.',
    employeesSubtitle: 'Manage employee records and employment status', addEmployee: 'Add Employee', editEmployee: 'Edit Employee', employeeId: 'Employee ID', employeeName: 'Employee Name', department: 'Department', status: 'Status', action: 'Action', searchEmployee: 'Search employee...', allDepartments: 'All departments', allStatuses: 'All statuses', active: 'Active', inactive: 'Inactive', noEmployeesFound: 'No employees found', addFirstEmployee: 'Start by adding the first employee.', adjustFilters: 'Try adjusting your search or filters.', selectDepartment: 'Select department', cancel: 'Cancel', saveChanges: 'Save Changes', saving: 'Saving...', edit: 'Edit', showing: 'Showing {from}–{to} of {total}', pageOf: 'Page {page} of {total}', employeeRequired: 'Employee ID, name, and department are required.', loadEmployeesError: 'Unable to load employees.', loadDepartmentsError: 'Unable to load departments.', saveEmployeeError: 'Unable to save employee.', loadEmployeeError: 'Unable to load employee.',
    absencesTitle: 'Employee Absences', absencesSubtitle: 'Track employee absences across the company', recordAbsence: 'Record Absence', date: 'Date', all: 'All', pending: 'Pending', excused: 'Excused', unexcused: 'Unexcused', actions: 'Actions', noAbsencesFound: 'No absences found', addFirstAbsence: 'Start by recording an employee absence.', editAbsence: 'Edit Absence', searchEmployeeLabel: 'Search employee', employeeIdOrName: 'Employee ID or name', employee: 'Employee', selectEmployee: 'Select employee', type: 'Type', absent: 'Absent', reason: 'Reason', notes: 'Notes', attendanceSource: 'Attendance Source', manual: 'Manual', absenceDetails: 'Absence Details', unknown: 'Unknown', view: 'View', delete: 'Delete', deleteAbsence: 'Delete Absence', deleteConfirmation: 'Are you sure you want to delete the absence record for {name} on {date}?', deleting: 'Deleting...', employeeDateRequired: 'Employee and date are required.', loadAbsencesError: 'Unable to load absences.', saveAbsenceError: 'Unable to save absence.', loadAbsenceError: 'Unable to load absence.', deleteAbsenceError: 'Unable to delete absence.',
    moduleComingSoon: 'Module coming soon', moduleComingHelp: 'This module is prepared and will be implemented in a later stage.', accessUnavailable: 'Access not available', accessHelp: 'Your account is not authorized for the requested department.', signOut: 'Sign out', idShort: 'ID', name: 'Name', previousPage: 'Previous page', nextPage: 'Next page'
  },
  ar: {
    language: 'اللغة', english: 'English', arabic: 'العربية', dashboard: 'لوحة التحكم', employees: 'الموظفون', delegations: 'تفويضات', absences: 'غيابات الموظفين', companyAbsences: 'غيابات الشركة', employeeDocuments: 'أوراق الموظفين', master: 'البيانات الأساسية', logout: 'تسجيل الخروج', humanResources: 'الموارد البشرية', hrDepartment: 'قسم الموارد البشرية', collectionFirm: 'شركة MIS للتحصيل',
    welcomeBack: 'مرحباً بعودتك', signInSubtitle: 'سجّل الدخول إلى حساب MIS', username: 'البريد الإلكتروني / اسم المستخدم', usernamePlaceholder: 'اسم المستخدم أو البريد الإلكتروني', password: 'كلمة المرور', passwordPlaceholder: 'أدخل كلمة المرور', rememberMe: 'تذكرني', forgotPassword: 'نسيت كلمة المرور؟', signIn: 'تسجيل الدخول', signingIn: 'جارٍ تسجيل الدخول', internalSystem: 'نظام الإدارة الداخلي', secureTagline: 'آمن. منظم. فعّال.', collectionSystem: 'نظام إدارة التحصيل', invalidCredentials: 'اسم المستخدم أو كلمة المرور غير صحيحة.', usernameRequired: 'البريد الإلكتروني أو اسم المستخدم مطلوب.', passwordRequired: 'كلمة المرور مطلوبة.',
    hrDashboard: 'لوحة تحكم الموارد البشرية', dashboardSubtitle: 'نظرة عامة على القوى العاملة وعمليات الموارد البشرية', totalEmployees: 'إجمالي الموظفين', activeEmployees: 'الموظفون النشطون', absentToday: 'الغائبون اليوم', documentsAttention: 'مستندات تحتاج إلى متابعة', allEmployeeRecords: 'جميع سجلات الموظفين', noEmployeeRecords: 'لا توجد سجلات موظفين بعد', totalEmployeePercent: '{value}% من إجمالي الموظفين', recordedToday: 'المسجل اليوم', notAvailableYet: 'غير متاح بعد', documentRecordsContext: '{count} سجل مستند · قواعد المتابعة غير متاحة', totalDocumentsContext: '{count} إجمالي المستندات', employeeOverview: 'نظرة عامة على الموظفين', noEmployeeData: 'لا توجد بيانات موظفين بعد', employeeDataHelp: 'سيظهر توزيع الموظفين حسب القسم عند توفر سجلات الموظفين.', quickActions: 'إجراءات سريعة', viewEmployeeDocuments: 'عرض أوراق الموظفين', attendanceOverview: 'نظرة عامة على الحضور', attendanceUnavailable: 'بيانات الحضور غير متاحة بعد', attendanceHelp: 'ستظهر بيانات الحضور بعد تنفيذ وحدة حضور الموارد البشرية.', recentActivity: 'النشاط الأخير', noRecentActivity: 'لا يوجد نشاط حديث', noActivitySource: 'لا يوجد حالياً مصدر لبيانات النشاط.', noDocumentsAttention: 'لا توجد مستندات تحتاج إلى متابعة', documentsAttentionHelp: 'لم يتم تحديد قواعد متابعة المستندات بعد. السجلات الحالية متاحة في أوراق الموظفين.', viewDocuments: 'عرض المستندات', dashboardUnavailable: 'لوحة التحكم غير متاحة', tryAgain: 'إعادة المحاولة', loadDashboardError: 'تعذر تحميل لوحة تحكم الموارد البشرية.',
    employeesSubtitle: 'إدارة سجلات الموظفين وحالة العمل', addEmployee: 'إضافة موظف', editEmployee: 'تعديل موظف', employeeId: 'رقم الموظف', employeeName: 'اسم الموظف', department: 'القسم', status: 'الحالة', action: 'الإجراء', searchEmployee: 'ابحث عن موظف...', allDepartments: 'كل الأقسام', allStatuses: 'كل الحالات', active: 'نشط', inactive: 'غير نشط', noEmployeesFound: 'لم يتم العثور على موظفين', addFirstEmployee: 'ابدأ بإضافة أول موظف.', adjustFilters: 'حاول تعديل البحث أو عوامل التصفية.', selectDepartment: 'اختر القسم', cancel: 'إلغاء', saveChanges: 'حفظ التغييرات', saving: 'جارٍ الحفظ...', edit: 'تعديل', showing: 'عرض {from}–{to} من {total}', pageOf: 'صفحة {page} من {total}', employeeRequired: 'رقم الموظف والاسم والقسم مطلوبة.', loadEmployeesError: 'تعذر تحميل الموظفين.', loadDepartmentsError: 'تعذر تحميل الأقسام.', saveEmployeeError: 'تعذر حفظ الموظف.', loadEmployeeError: 'تعذر تحميل الموظف.',
    absencesTitle: 'غيابات الموظفين', absencesSubtitle: 'متابعة غياب الموظفين داخل الشركة', recordAbsence: 'تسجيل غياب', date: 'التاريخ', all: 'الكل', pending: 'قيد المراجعة', excused: 'بعذر', unexcused: 'بدون عذر', actions: 'الإجراءات', noAbsencesFound: 'لا توجد حالات غياب', addFirstAbsence: 'ابدأ بتسجيل غياب موظف.', editAbsence: 'تعديل الغياب', searchEmployeeLabel: 'بحث عن موظف', employeeIdOrName: 'رقم الموظف أو الاسم', employee: 'الموظف', selectEmployee: 'اختر الموظف', type: 'النوع', absent: 'غائب', reason: 'السبب', notes: 'ملاحظات', attendanceSource: 'مصدر الحضور', manual: 'يدوي', absenceDetails: 'تفاصيل الغياب', unknown: 'غير معروف', view: 'عرض', delete: 'حذف', deleteAbsence: 'حذف الغياب', deleteConfirmation: 'هل أنت متأكد من حذف غياب {name} بتاريخ {date}؟', deleting: 'جارٍ الحذف...', employeeDateRequired: 'الموظف والتاريخ مطلوبان.', loadAbsencesError: 'تعذر تحميل الغيابات.', saveAbsenceError: 'تعذر حفظ الغياب.', loadAbsenceError: 'تعذر تحميل الغياب.', deleteAbsenceError: 'تعذر حذف الغياب.',
    moduleComingSoon: 'الوحدة قيد الإعداد', moduleComingHelp: 'تم تجهيز هذه الوحدة وسيتم تنفيذها في مرحلة لاحقة.', accessUnavailable: 'الوصول غير متاح', accessHelp: 'حسابك غير مصرح له بالوصول إلى القسم المطلوب.', signOut: 'تسجيل الخروج', idShort: 'الرقم', name: 'الاسم', previousPage: 'الصفحة السابقة', nextPage: 'الصفحة التالية'
  }
} as const;

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;
